### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by sarangbaheti** [pattex/jekyll-tagging#35]
I am running into this error while building a site with tagging plugin.
(I have added this in octopress, don't think it should matter).

Any help in this matter is much appreciated.

followed all steps up about setting up plugin (gem install, tweaking _config.yml, defining tag_page layout and ext.rb requiring jekyll/tagging.rb)

jekyll build --trace
-------
/var/lib/gems/2.1.0/gems/jekyll-tagging-0.6.0/lib/jekyll/tagging.rb:41:in `join': no implicit conversion of nil into String (TypeError)
	from /var/lib/gems/2.1.0/gems/jekyll-tagging-0.6.0/lib/jekyll/tagging.rb:41:in `block in new_tag'
	from /var/lib/gems/2.1.0/gems/jekyll-tagging-0.6.0/lib/jekyll/tagging.rb:33:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-tagging-0.6.0/lib/jekyll/tagging.rb:33:in `new_tag'
	from /var/lib/gems/2.1.0/gems/jekyll-tagging-0.6.0/lib/jekyll/tagging.rb:29:in `block in generate_tag_pages'
	from /var/lib/gems/2.1.0/gems/jekyll-tagging-0.6.0/lib/jekyll/tagging.rb:29:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-tagging-0.6.0/lib/jekyll/tagging.rb:29:in `generate_tag_pages'
	from /var/lib/gems/2.1.0/gems/jekyll-tagging-0.6.0/lib/jekyll/tagging.rb:19:in `generate'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:280:in `block in generate'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:279:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:279:in `generate'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:50:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

**Comment by sarangbaheti** [comment]
after further debugging found that you need to define tag_page_dir in _config.yml
could you please fixup doc to say that along with tag_dir one needs to define tag_page_dir as well?
