### ISSUE TITLE
Cannot require.

### ISSUE THREAD

**Issue by matthiasbeyer** [pattex/jekyll-tagging#7]
I followed your instructions and did

```
gem install jekyll-tagging
```

and insert a file `extr.rb` in `./plugins` and insert

```
require 'jekyll/tagging'
```

but it results in the following error:

```
/home/matthias/blog/plugins/ext.rb:1:in `require': cannot load such file -- jekyll-tagging (LoadError)
        from /home/matthias/blog/plugins/ext.rb:1:in `<top (required)>'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/lib/jekyll/site.rb:76:in `require'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/lib/jekyll/site.rb:76:in `block in setup'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/lib/jekyll/site.rb:75:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/lib/jekyll/site.rb:75:in `setup'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/lib/jekyll/site.rb:30:in `initialize'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/bin/jekyll:224:in `new'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/bin/jekyll:224:in `<top (required)>'
        from /usr/bin/jekyll:19:in `load'
        from /usr/bin/jekyll:19:in `<main>'
```

kind regards.

**Comment by ozgrozer** [comment]
I did everything exactly. But I have same problem now.

```
$ gem which jekyll/tagging

/Users/mac/.rvm/gems/ruby-2.4.2/gems/jekyll-tagging-1.1.0/lib/jekyll/tagging.rb
```

```
$ jekyll build

Configuration file: /Applications/XAMPP/xamppfiles/htdocs/dasper/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-tagging or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-tagging' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
jekyll 3.5.2 | Error:  jekyll-tagging
```

```
$ gem env

RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.13
  - RUBY VERSION: 2.4.2 (2017-09-14 patchlevel 198) [x86_64-darwin17]
  - INSTALLATION DIRECTORY: /Users/mac/.rvm/gems/ruby-2.4.2
  - USER INSTALLATION DIRECTORY: /Users/mac/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /Users/mac/.rvm/rubies/ruby-2.4.2/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/mac/.rvm/gems/ruby-2.4.2/bin
  - SPEC CACHE DIRECTORY: /Users/mac/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/mac/.rvm/rubies/ruby-2.4.2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-17
  - GEM PATHS:
     - /Users/mac/.rvm/gems/ruby-2.4.2
     - /Users/mac/.rvm/gems/ruby-2.4.2@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/mac/.rvm/gems/ruby-2.4.2/bin
     - /Users/mac/.rvm/gems/ruby-2.4.2@global/bin
     - /Users/mac/.rvm/rubies/ruby-2.4.2/bin
     - /Users/mac/.rvm/bin
     - /Library/Frameworks/Python.framework/Versions/3.5/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
```
