### ISSUE TITLE
NoMethodError when trying the example from the Readme

### ISSUE THREAD

**Issue by matthiasbeyer** [pattex/jekyll-tagging#8]
My plugins/ext.rb:

```
~/blog$ cat plugins/ext.rb 
require 'jekyll/tagging
```

The part in the `_config.yml`:

```
~/blog$ cat _config.yml | grep tag
tag_page_layout: tag_page
tag_page_tag: tag
```

My tag site:

```
~/blog$ cat source/tags.html 

---
layout: page
title: "tags"
date: 2012-11-29 12:35
comments: true
sharing: true
footer: true

---

<h2>{{ page.tag }}</h2>
<ul>
{% for post in page.posts %}
  <li><a href="{{ post.url }}">{{ post.title }}</a> ({{ post.date | date_to_string }} | Tags: {{ post | tags }})</li>
{% endfor %}
</ul>

<div id="tag-cloud">
  {{ site | tag_cloud }}
</div>
```

The error:

```
/home/matthias/.gem/ruby/1.9.1/gems/jekyll-tagging-0.4.0/lib/jekyll/tagging.rb:41:in `block in new_tag': undefined method `ext' for nil:NilClass (NoMethodError)
        from /home/matthias/.gem/ruby/1.9.1/gems/jekyll-tagging-0.4.0/lib/jekyll/tagging.rb:33:in `each'
        from /home/matthias/.gem/ruby/1.9.1/gems/jekyll-tagging-0.4.0/lib/jekyll/tagging.rb:33:in `new_tag'
        from /home/matthias/.gem/ruby/1.9.1/gems/jekyll-tagging-0.4.0/lib/jekyll/tagging.rb:29:in `block in generate_tag_pages'
        from /home/matthias/.gem/ruby/1.9.1/gems/jekyll-tagging-0.4.0/lib/jekyll/tagging.rb:29:in `each'
        from /home/matthias/.gem/ruby/1.9.1/gems/jekyll-tagging-0.4.0/lib/jekyll/tagging.rb:29:in `generate_tag_pages'
        from /home/matthias/.gem/ruby/1.9.1/gems/jekyll-tagging-0.4.0/lib/jekyll/tagging.rb:19:in `generate'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/lib/jekyll/site.rb:184:in `block in generate'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/lib/jekyll/site.rb:183:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/lib/jekyll/site.rb:183:in `generate'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/lib/jekyll/site.rb:39:in `process'
        from /usr/lib/ruby/gems/1.9.1/gems/jekyll-0.11.2/bin/jekyll:250:in `<top (required)>'
        from /usr/bin/jekyll:19:in `load'
        from /usr/bin/jekyll:19:in `<main>'
```

**Comment by nhoizey** [comment]
I also got the ```undefined method `ext' for nil:NilClass (NoMethodError)``` error, because I had the ```atom-tag.xml``` in the root directory (as my ```atom.xml```) but it should be in ```_layouts/```

**Comment by Toiya** [comment]
Hi! I'm also having this issue, but I can't figure out what's wrong.
My _plugins/ext.rb:
```
require 'jekyll/tagging'
```
_config.yml:
```
plugins:
  - jekyll/tagging

# Jekyll-tagging plugin  
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
```
Gemfile:
```
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end

gem 'jekyll-tagging'
```
tag-page.html is in _layouts folder, and the error message is:
```
jekyll 3.8.4 | Error:  undefined method `ext' for nil:NilClass
```

Thank you so much in advance!

**Comment by HibikeQuantum** [comment]
```
.rbenv/versions/2.6.10/lib/ruby/gems/2.6.0/gems/jekyll-tagging-1.1.0/lib/jekyll/tagging.rb:61:in `block in new_tag': undefined method `ext' for nil:NilClass (NoMethodError)
```
In My case, After making `_includes/tag_page.html` Then the error message disappeared.
